### ISSUE TITLE
Multiple Sidebar Popups

### ISSUE THREAD

**Issue by Pi-Cla** [opentripplanner/otp-react-redux#1104]
Is there any way to set multiple sidebar links via config.yml?
Right now it seems like I can only set a single link to appear in the sidebar

**Comment by miles-grant-ibigroup** [comment]
Does this work for you?

```yaml
extraMenuItems:
  - id: sidebar
    containsChildren: "true"
    children:
      - id: first-item
        label: First Item
        iconType: "any-font-awesome-icon"
        href: "example.com"
      - id: second-item
        href: "https://example.com/"
```
