### ISSUE TITLE
environment vars in config.yml

### ISSUE THREAD

**Issue by stemove** [opentripplanner/otp-react-redux#244]
hi

I just dockerized this application within a docker compose services

my OTP is in another container in the same environment
I would like to pass some variables in the configuration including **host** and **port** through the environment variables

do you have any ideas on how to achieve this?
I can only think of a tool that dynamically build config.yml and then the application build is started.

```yml
api:
  host: http://localhost
  path: /otp/routers/default
  port: 8080
```
to this way
```yml
api:
  host: http://${OTP_HOST}
  path: /otp/routers/default
  port: ${OTP_PORT}
```
