### ISSUE TITLE
Example app doesn't start

### ISSUE THREAD

**Issue by leonardehrenfried** [opentripplanner/otp-react-redux#72]
I tried to use the example app and followed the instructions but I get the following error: `TypeError: _toJS is undefined`;\\
![Screenshot from 2019-07-04 14-34-29](https://user-images.githubusercontent.com/151346/60667174-2752c000-9e69-11e9-8bd5-9fe6e7d58205.png)

(I'm on Firefox on Linux, if it matters.)

I've added the `config.yaml` file and it's contents are:

```yml
api:
  host: http://localhost
  path: /otp/routers/default
  port: 8080
# Add suggested locations to be shown as options in the form view.
# locations:
#   - id: 'airport'
#     icon: 'plane'
#     name: 'Portland International Airport (PDX)'
#     lat: 45.587579
#     lon: -122.593084
#   - id: 'zoo'
#     icon: building
#     lat: 45.51010444232195
#     lon: -122.71607145667079
#     name: Oregon Zoo, Portland, OR

### The persistence setting is used to enable the storage of places (home, work),
### recent searches/places, user overrides, and favorite stops. Currently the
### only strategy is localStorage (which is used by default). It also must be
### enabled to show the stored locations (see above).
### TODO: add another server-based strategy
persistence:
  enabled: true
  strategy: localStorage

map:
  initLat: 45.52
  initLon: -122.682
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
    - name: Stamen Toner Lite
      url: http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'

geocoder:
  boundary:
    rect:
      minLon: -123.2034
      maxLon: -122.135
      minLat: 45.273
      maxLat: 45.7445
  MAPZEN_KEY: gAZxU6e1RamAot9wPp0_lA
  focusPoint:
    lat: 45.5223452
    lon: -122.6821804
  # Optional custom Pelias instance (defaults to Mapzen Search)
  # baseUrl: https://geocoder.example.com/pelias/v1

# Use this mode config for the enhanced Transit+ config
modes:
  transitModes:
    - mode: BUS
      label: Bus
    - mode: TRAM
      label: MAX & Streetcar
    - mode: RAIL
      label: WES
    - mode: GONDOLA
      label: Aerial Tram

  accessModes:
    - mode: BICYCLE
      label: Transit + Bike

  bicycleModes:
    - mode: BICYCLE
      label: Own Bike
      iconWidth: 18


routingTypes:
  - key: ITINERARY
    text: Exact Time

### Use this config for the standard mode selector
# modeGroups:
#   - name: Transit
#     modes:
#       - TRAM
#       - BUS
#   - name: Walk/Bike
#     modes:
#       - WALK
#       - BICYCLE
```

What am I doing wrong?
